### ISSUE TITLE
Dshot speed?

### ISSUE THREAD

**Issue by BlackXDragon** [dmrlawson/raspberrypi-dshot#1]
Hey, I'd like to use your implementation for my own Raspberry Pi quadcopter. Could you please tell me which speed of Dshot does your code work on?

The ESC I'm planning on using is [Holybro Tekko32 35A BLHeli_32 Dshot1200](https://www.banggood.in/4X-Holybro-Tekko32-35A-BLHeli_32-ESC-Dshot1200-2-6S-Build-In-Current-Sensor-For-RC-Drone-FPV-Racing-p-1244743.html?p=0L28031408639201503Y&cur_warehouse=CN).
Is this ESC compatible with your code?

**Comment by dmrlawson** [comment]
Hi,

The timings are set up for Dshot 150. I think this will be compatible with those ESCs. 

Don't expect too much, I've had my quadcopter hovering without using any sensors, but it think when the CPU heats up (because of the busy loop in the code) it changes frequency and breaks the Dshot timings. 

If you want something more reliable I would suggest trying PWM.

**Comment by BlackXDragon** [comment]
Should I try some other protocol such as Multishot?

**Comment by dmrlawson** [comment]
You could have a go. The raspberry pi isn't really suited to this, although this project seems to have got it working with PWM: https://github.com/dridri/bcflight

**Comment by BlackXDragon** [comment]
Cool! Thanks!
